name: cetapil_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.6+11

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  connectivity_plus: ^6.0.5
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  video_player: ^2.9.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  dropdown_search: ^6.0.1
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_pdfview: ^1.3.4
  dio: ^5.7.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.svg
    - assets/icon/
    - assets/icon/setting_account.svg
    - assets/icon.png

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700